# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CirconusUnifiedAgent < Formula
  desc "Circonus Unified Agent"
  homepage "https://circonus.com"
  version "0.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/circonus-labs/circonus-unified-agent/releases/download/v0.2.3/circonus-unified-agent_0.2.3_darwin_arm64.tar.gz"
      sha256 "7c0c1f334e1eac84449be70f6d750ae66e48237ced546050cde894755d849012"

      def install
        sbin.install "sbin/circonus-unified-agentd"
        pkgetc.install "etc/example-circonus-unified-agent.conf" => "circonus-unified-agent.conf"
        (pkgetc/"conf.d").mkpath
        doc.install "README.md", "LICENSE"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/circonus-labs/circonus-unified-agent/releases/download/v0.2.3/circonus-unified-agent_0.2.3_darwin_x86_64.tar.gz"
      sha256 "116a096fed567171b81937727bb2f66f968bd6468dd7403bc59fd6a02cc27f9b"

      def install
        sbin.install "sbin/circonus-unified-agentd"
        pkgetc.install "etc/example-circonus-unified-agent.conf" => "circonus-unified-agent.conf"
        (pkgetc/"conf.d").mkpath
        doc.install "README.md", "LICENSE"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/circonus-labs/circonus-unified-agent/releases/download/v0.2.3/circonus-unified-agent_0.2.3_linux_arm64.tar.gz"
      sha256 "a65f36133845f5596ad0e608ec7b02c05af89205585cd040461cb0e631def77f"

      def install
        sbin.install "sbin/circonus-unified-agentd"
        pkgetc.install "etc/example-circonus-unified-agent.conf" => "circonus-unified-agent.conf"
        (pkgetc/"conf.d").mkpath
        doc.install "README.md", "LICENSE"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/circonus-labs/circonus-unified-agent/releases/download/v0.2.3/circonus-unified-agent_0.2.3_linux_x86_64.tar.gz"
      sha256 "dc5c7a93a0a95e76c560b9e8a96cf25f31f9171457753360b2ffc200f5dd9d17"

      def install
        sbin.install "sbin/circonus-unified-agentd"
        pkgetc.install "etc/example-circonus-unified-agent.conf" => "circonus-unified-agent.conf"
        (pkgetc/"conf.d").mkpath
        doc.install "README.md", "LICENSE"
      end
    end
  end

  def caveats
    <<~EOS
      1. Edit #{pkgetc}/circonus-unified-agent.conf to add your API key.
      2. Run brew services start circonus-unified-agent

      Or, if upgrading, brew services restart circonus-unified-agent
    EOS
  end

  service do
    run [opt_sbin/"circonus-unified-agentd", "--config", etc/"circonus-unified-agent/circonus-unified-agent.conf", "--config-directory", etc/"circonus-unified-agent/conf.d"]
    keep_alive true
    log_path var/"log/circonus-unified-agent.log"
    error_log_path var/"log/circonus-unified-agent.log"
  end

  test do
    system "#{sbin}/circonus-unified-agentd --version"
  end
end
