# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CirconusUnifiedAgent < Formula
  desc "Circonus Unified Agent"
  homepage "https://circonus.com"
  version "0.2.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/circonus-labs/circonus-unified-agent/releases/download/v0.2.8/circonus-unified-agent_0.2.8_darwin_arm64.tar.gz"
      sha256 "87e980bba5ac3f9af94dfa84d0abe42371b1b24a8149a2df3f17e6f442bfa1a8"

      def install
        sbin.install "sbin/circonus-unified-agentd"
        pkgetc.install "etc/example-circonus-unified-agent.conf" => "circonus-unified-agent.conf"
        (pkgetc/"conf.d").mkpath
        doc.install "README.md", "LICENSE"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/circonus-labs/circonus-unified-agent/releases/download/v0.2.8/circonus-unified-agent_0.2.8_darwin_amd64.tar.gz"
      sha256 "4059e3eba1c34ecf8c9bc4079063a75f189366f3c78c23208a38f2c0585cb8ba"

      def install
        sbin.install "sbin/circonus-unified-agentd"
        pkgetc.install "etc/example-circonus-unified-agent.conf" => "circonus-unified-agent.conf"
        (pkgetc/"conf.d").mkpath
        doc.install "README.md", "LICENSE"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/circonus-labs/circonus-unified-agent/releases/download/v0.2.8/circonus-unified-agent_0.2.8_linux_arm64.tar.gz"
      sha256 "ee481c3d0c85838a8e81ae4cf469042a4bf6878a3b7a8f48f6d1356ca5bddf3f"

      def install
        sbin.install "sbin/circonus-unified-agentd"
        pkgetc.install "etc/example-circonus-unified-agent.conf" => "circonus-unified-agent.conf"
        (pkgetc/"conf.d").mkpath
        doc.install "README.md", "LICENSE"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/circonus-labs/circonus-unified-agent/releases/download/v0.2.8/circonus-unified-agent_0.2.8_linux_amd64.tar.gz"
      sha256 "af42788c5eb62ab766e1710bde40fa66682b24f2315139f4ea73c021eac32bab"

      def install
        sbin.install "sbin/circonus-unified-agentd"
        pkgetc.install "etc/example-circonus-unified-agent.conf" => "circonus-unified-agent.conf"
        (pkgetc/"conf.d").mkpath
        doc.install "README.md", "LICENSE"
      end
    end
  end

  def caveats
    <<~EOS
      1. Edit #{plist_name} and add your API token in API_TOKEN environment variable setting
      2. Run "brew services start circonus-unified-agent"

      Or, if upgrading, run "brew services restart circonus-unified-agent"
    EOS
  end

  service do
    run [opt_sbin/"circonus-unified-agentd", "--config", etc/"circonus-unified-agent/circonus-unified-agent.conf", "--config-directory", etc/"circonus-unified-agent/conf.d"]
    keep_alive true
    log_path var/"log/circonus-unified-agent.log"
    error_log_path var/"log/circonus-unified-agent.log"
  end

  test do
    system "#{sbin}/circonus-unified-agentd --version"
  end
end
